// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vP3sqqqi2QrPX0AsDQH5NFksrqLYPV4',
    appId: '1:857340004927:web:82e0a63c95ff1ebcc4468a',
    messagingSenderId: '857340004927',
    projectId: 'instagram-tut-3e2ee',
    authDomain: 'instagram-tut-3e2ee.firebaseapp.com',
    storageBucket: 'instagram-tut-3e2ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYe0mj7aSsH-TXvpJWMYfV2WPHzeQhs5U',
    appId: '1:857340004927:android:0ad5c9acf4a89ee4c4468a',
    messagingSenderId: '857340004927',
    projectId: 'instagram-tut-3e2ee',
    storageBucket: 'instagram-tut-3e2ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAstX6lPxKkybiTPYqkj3P4fOFP_67VtGg',
    appId: '1:857340004927:ios:1a82f146e2d1d67bc4468a',
    messagingSenderId: '857340004927',
    projectId: 'instagram-tut-3e2ee',
    storageBucket: 'instagram-tut-3e2ee.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAstX6lPxKkybiTPYqkj3P4fOFP_67VtGg',
    appId: '1:857340004927:ios:baa43e1fb10c69bac4468a',
    messagingSenderId: '857340004927',
    projectId: 'instagram-tut-3e2ee',
    storageBucket: 'instagram-tut-3e2ee.appspot.com',
    iosBundleId: 'com.example.firstapp.RunnerTests',
  );
}
